### ISSUE TITLE
4dtv calculation

### ISSUE THREAD

**Issue by bostanict** [JinfengChen/Scripts#2]
Hi. Thanks for the effort and nice scripts.

I am interested in the 4dtv analyses . Can you please specify the order each script file should be ran and the input files for each one?

Its quite difficult for a non expert to understand the order and also the format required for each script

Thank you

**Comment by scotty323** [comment]
same question. how to calculate 4dtv???

**Comment by JinfengChen** [comment]
Check this one, https://raw.githubusercontent.com/JinfengChen/Scripts/master/FFgenome/03.evolution/distance_kaks_4dtv/bin/calculate_4DTV_correction.pl.

**Comment by bostanict** [comment]
Hi Jinfeng,

thanks a lot. Does it work also for the sequences with NOT EQUAL length as well? or the sequences must be the same length?

Best,
Hamed

**Comment by JinfengChen** [comment]
I think the sequences have to be aligned. I did not use the script for a long time. You need to figure out yourself.

**Comment by bostanict** [comment]
Thanks a lot. I found before a script which is for similar length sequences. I did not find anything for those not similar in length.

**Comment by scotty323** [comment]
What is format of pairwise alignment for input file in script calculate_4DTV_correction.pl?
fasta? phylip? or something else?
Thanks!

**Comment by JinfengChen** [comment]
The format is AXT. 
https://genome.ucsc.edu/goldenPath/help/axt.html

#!/usr/bin/perl 
use strict;

##author: sun ming'an, sunma@genomics.org.cn
##modifier: fanwei, fanw@genomics.org.cn
##correction: LiJun, junli@genomics.org.cn
##Date: 2008-9-24

##4dtv (transversion rate on 4-fold degenerated sites) are calculated with HKY substitution models 
##Reference: M. Hasegawa, H. Kishino, and T. Yano, J. Mol. Evol. 22 (2), 160 (1985)

die "perl $0 AXTfile > outfile\n" unless( @ARGV == 1);

**Comment by scotty323** [comment]
Thank you! I got result.
tao@PowerEdge-T620:~/Scripts/FFgenome/03.evolution/distance_kaks_4dtv/bin> perl calculate_4DTV_correction.pl zz_align1
tag     4dtv_corrected  4dtv_raw        condon_4d       codon_4dt
align   0.0855875465959473      0.08    125     10


so, is "4dtv_corrected"  the value that is used for estimation of homologue divergence time?

**Comment by JinfengChen** [comment]
Yes, I believe it is.

**Comment by scotty323** [comment]
:+1: :100:

**Comment by yangxiaofeill** [comment]
Thanks for your scripts.
When I run the calculate_evoultion_distance.pl, the error message is "Can't locate GACP.pm in @INC". I searched the "GACP" module but cannot find. Could you please tell me where can I donwloaded the  GACP module or how to install it?

**Comment by JinfengChen** [comment]
Anyone who uses the script "calculate_4DTV_correction.pl" should read this post first. There are errors in the original script. I updated the script to fix the error in % codons. Please make sure you are using the updated script. Thanks.
https://www.jianshu.com/p/6d704378c342

**Comment by neel404** [comment]
> Thanks for your scripts. When I run the calculate_evoultion_distance.pl, the error message is "Can't locate GACP.pm in @inc". I searched the "GACP" module but cannot find. Could you please tell me where can I donwloaded the GACP module or how to install it?

You were able to fix it? I am facing the same error.
