### ISSUE TITLE
calculate_4DTV_correction.pl脚本的密码子有错误

### ISSUE THREAD

**Issue by ShuaiNIEgithub** [JinfengChen/Scripts#4]
详见热心同学的建议
https://www.jianshu.com/p/6d704378c342

**Comment by JinfengChen** [comment]
Thank you so much for pointing out the error. I never used the script myself. I learned from the post that many people are using it. I made changes to the original script to avoid misleading others. The credit of the script should belong to BGI and the authors listed in the script.

Jinfeng
